sudo: required

language: ruby

services:
  - docker

before_install:
  #- gem install serverspec
  #- gem install docker-api

script:
  #- rspec Dockerfile_spec.rb
  - sudo docker build -t pyload .
  # TODO: rspec surely is much cooler than this
  - sudo sh ./test-link.sh 'xdcc://irc.rizon.net/#NIBL/ARUTHA-BATCH|720p/#1'
